<a href="https://colab.research.google.com/github/navyavemavarapu/Guvi_Tasks/blob/main/Task2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)

1.21.6


In [3]:
print(np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [4]:
null_vector = np.zeros(10)

In [5]:
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [6]:
print(null_vector.size)
print(null_vector.itemsize)

10
8


In [7]:
#size of array = array.size
#Memory size of one array element in bytes = array.itemsize
print("Memory size of array in bytes is: ",null_vector.size * null_vector.itemsize)

Memory size of array in bytes is:  80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [8]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [9]:
null_vect2 = np.zeros(10)

In [10]:
null_vect2[4] = 1

In [11]:
print(null_vect2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [12]:
print(np.arange(10,50))
#last element will not be included

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [13]:
array1 = np.array([1,2,3,4,5,6,7,8])

In [14]:
print(array1[::-1])

[8 7 6 5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [15]:
a = np.array([0,1,2,3,4,5,6,7,8])

In [16]:
print(np.reshape(a, (3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [17]:
notnon_zero = np.array([1,2,0,0,4,0])

In [18]:
np.nonzero(notnon_zero)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [19]:
print(np.eye(3, dtype = 'int' )) #default datatype is float

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [20]:
print(np.random.random((3,3,3)))

[[[0.59898997 0.66045286 0.84469097]
  [0.86991699 0.95991891 0.01912609]
  [0.28738909 0.89562136 0.8023728 ]]

 [[0.94970377 0.30955553 0.98667292]
  [0.57844032 0.83437783 0.84541566]
  [0.69481874 0.31289528 0.80385705]]

 [[0.4909634  0.06793077 0.27319918]
  [0.36898865 0.92905264 0.19914591]
  [0.64729443 0.31798758 0.24825672]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [21]:
a = np.random.random((10,10))

In [22]:
print(a)

[[0.20343837 0.98896518 0.2171664  0.92361999 0.26677137 0.50169371
  0.59231294 0.34886059 0.91753739 0.52401099]
 [0.00671885 0.43492962 0.18562297 0.3739383  0.482852   0.77010065
  0.33918614 0.94429441 0.68385474 0.64166436]
 [0.10037368 0.3656001  0.26424658 0.52606134 0.14179048 0.41718345
  0.31812563 0.14907792 0.0936925  0.66096145]
 [0.99742944 0.72444176 0.4729411  0.57952772 0.67434786 0.44948769
  0.32085888 0.55745712 0.55522663 0.27205106]
 [0.32714886 0.57320273 0.86654312 0.03723982 0.268753   0.91830952
  0.04901127 0.45282331 0.76808055 0.80333923]
 [0.76502827 0.00278043 0.10017044 0.63515161 0.78586564 0.94362411
  0.01551655 0.52679578 0.21719158 0.13503293]
 [0.90768919 0.52309103 0.55669088 0.45627823 0.14530243 0.88545416
  0.65439993 0.51428918 0.59365935 0.83248848]
 [0.34107014 0.39071814 0.04263826 0.20993459 0.90867029 0.43836822
  0.15719297 0.61093861 0.59652185 0.68705013]
 [0.05040409 0.33028308 0.89751575 0.12731379 0.4798614  0.38623885
  0.62772153

In [23]:
print(np.min(a))

0.002780428635348886


In [24]:
print(np.max(a))

0.997429443965611


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [25]:
rand_vect = np.random.random((30))

In [26]:
print(rand_vect)

[0.40307565 0.270324   0.02884106 0.08797989 0.12164313 0.52654117
 0.34434294 0.46795001 0.84923753 0.80181268 0.29776862 0.84623053
 0.96596776 0.54205936 0.67036924 0.73915311 0.96973594 0.26761372
 0.93600946 0.11159937 0.34928632 0.26477676 0.28504139 0.66885526
 0.69981286 0.74486331 0.10381722 0.28423718 0.52985055 0.88519552]


In [27]:
print(np.mean(rand_vect))

0.5021330518323168


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [28]:
twod_array = np.ones((5,5),dtype='int')

In [146]:
twod_array[1:-1,1:-1] = 0
print(twod_array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [32]:
existing_array = np.ones((3,3), dtype = 'int')

In [33]:
print(existing_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [34]:
print(np.pad(existing_array, pad_width=1, mode='constant'))

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? 


(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [35]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [36]:
dd_array = np.diag(np.arange(1,5), k = -1)

In [37]:
print(dd_array)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [38]:
checkboard = np.ones((8,8), dtype='int')

In [39]:
checkboard[::2, ::2] = 0

In [40]:
checkboard[1::2, 1::2] = 0

In [41]:
print(checkboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [42]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [43]:
array= np.array([[0,1], [1,0]])
print(np.tile(array,(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [44]:
normalize = np.random.random((5,5))
min = normalize.min()
max = normalize.max()
print((normalize-min)/(max - min))

[[0.28076108 0.30308097 0.09338815 0.41741325 0.80342913]
 [0.96715748 0.92798935 0.43940659 0.79544315 0.85186969]
 [0.         0.73660619 0.15427111 0.42458089 0.75096011]
 [0.94989395 0.50322553 0.162333   1.         0.80368924]
 [0.96093698 0.87768171 0.70883063 0.82361197 0.75635604]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [45]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [46]:
a= np.dot(np.ones((5,3),dtype='int'), np.ones((3,2),dtype='int'))
print (a)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [47]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [48]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [49]:
Z = np.array([0,1,2,3,4,5])
print(Z**Z)
print(2<< Z >>2)
print(Z<- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z)---error

[   1    1    4   27  256 3125]
[ 0  1  2  4  8 16]
[False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[0. 1. 2. 3. 4. 5.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [50]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [51]:
s = np.random.uniform(-1,1,5)
# print(np.copysign(s,+1))
np.ceil(s)
# np.abs(s)

array([ 1.,  1., -0.,  1., -0.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [52]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 2 6 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [53]:
print(np.seterr())
print(np.errstate())

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [54]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [55]:
ystrd = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",ystrd)
tdy = np.datetime64('today', 'D')
print("Today: ",tdy)
tmrw  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tmrw)

Yestraday:  2022-05-13
Today:  2022-05-14
Tomorrow:  2022-05-15


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [56]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [57]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [58]:
Z = np.linspace(1,2,10)
print(Z)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [59]:
print(Z - Z%1)
print(np.ceil(Z))
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 2.]
[1. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 2.]
[1 1 1 1 1 1 1 1 1 2]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [60]:
arr1 = np.zeros((5,5))
arr2 = np.arange(5)

In [61]:
print(arr1+arr2)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [62]:
def generate(): 
    for i in range(10):
        yield i
        
Z = np.fromiter(generate(), dtype=int)
print (Z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [63]:
arrayy = np.linspace(0,1,12,endpoint=True)[1:-1]
print(arrayy)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [64]:
rand_vector = np.random.random(10)

In [65]:
rand_vector.sort()

In [66]:
print(rand_vector)

[0.03077105 0.16895542 0.20841367 0.26072014 0.2789912  0.36585636
 0.53488211 0.57326149 0.75975434 0.92939434]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [67]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [68]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
x = np.allclose(A,B)
print(x)
np.array_equal(A,B)

False


False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [151]:
z=np.arange(0,10)
print(z)
z.flags.writeable=False
z[2]=100
z

[0 1 2 3 4 5 6 7 8 9]


ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [71]:
Z = np.random.random((10,2))

In [72]:
X,Y = Z[:,0], Z[:,1]

In [73]:
R = np.sqrt(X**2+Y**2)

In [74]:
T = np.arctan2(Y,X)

In [75]:
print(R)
print(T)

[0.47517697 0.83110426 0.93955564 1.06297375 0.81169068 0.42682196
 0.98452452 0.26252235 1.05139076 1.19384312]
[0.70146635 1.38709577 0.10712115 0.89259086 0.22863845 0.73715768
 0.27497537 0.55076493 0.89214151 0.67534495]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [76]:
rand_vectorrr = np.random.random(10)

In [77]:
rand_vectorrr[rand_vectorrr.argmax()] = 0

In [78]:
print(rand_vectorrr)

[0.43437305 0.58564027 0.60982016 0.00944753 0.5313469  0.31747622
 0.3781002  0.63930169 0.1309147  0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [148]:
a = np.zeros((10,10), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
a

array([[(0.        , 0.        ), (0.11111111, 0.        ),
        (0.22222222, 0.        ), (0.33333333, 0.        ),
        (0.44444444, 0.        ), (0.55555556, 0.        ),
        (0.66666667, 0.        ), (0.77777778, 0.        ),
        (0.88888889, 0.        ), (1.        , 0.        )],
       [(0.        , 0.11111111), (0.11111111, 0.11111111),
        (0.22222222, 0.11111111), (0.33333333, 0.11111111),
        (0.44444444, 0.11111111), (0.55555556, 0.11111111),
        (0.66666667, 0.11111111), (0.77777778, 0.11111111),
        (0.88888889, 0.11111111), (1.        , 0.11111111)],
       [(0.        , 0.22222222), (0.11111111, 0.22222222),
        (0.22222222, 0.22222222), (0.33333333, 0.22222222),
        (0.44444444, 0.22222222), (0.55555556, 0.22222222),
        (0.66666667, 0.22222222), (0.77777778, 0.22222222),
        (0.88888889, 0.22222222), (1.        , 0.22222222)],
       [(0.        , 0.33333333), (0.11111111, 0.33333333),
        (0.22222222, 0.33333333), (0.

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [149]:
X = np.arange(1,5).reshape(2,2)
print(X)
Y = np.arange(5,9).reshape(2,2)
print(Y)
C = (1/(np.subtract.outer(X,Y)))
C

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[[[-0.25      , -0.2       ],
         [-0.16666667, -0.14285714]],

        [[-0.33333333, -0.25      ],
         [-0.2       , -0.16666667]]],


       [[[-0.5       , -0.33333333],
         [-0.25      , -0.2       ]],

        [[-1.        , -0.5       ],
         [-0.33333333, -0.25      ]]]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [80]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [81]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [82]:
Z = np.arange(100)
print(Z)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin()
print(index)
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
31.352318707097826
31
31


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [83]:
sat_array = np.ones(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(sat_array)

[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))]


/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py:204: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = empty(shape, dtype, order)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [84]:
vector = np.random.random((10,2))

In [85]:
X,Y = np.atleast_2d(vector[:,0]), np.atleast_2d(vector[:,1])

In [86]:
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.89968457 0.98297748 1.07813079 0.95245071 0.86531322
  0.79532557 0.33493555 0.19635252 0.33169684]
 [0.89968457 0.         0.38157274 0.19998765 0.58335947 0.0343831
  0.16034497 0.81731454 0.82557066 0.57189648]
 [0.98297748 0.38157274 0.         0.32876542 0.95951335 0.38455322
  0.50972741 0.76890716 0.98457614 0.71459255]
 [1.07813079 0.19998765 0.32876542 0.         0.73435137 0.230883
  0.35694944 0.95494187 1.01810265 0.75728089]
 [0.95245071 0.58335947 0.95951335 0.73435137 0.         0.57551898
  0.45395074 1.07174206 0.77950087 0.68384285]
 [0.86531322 0.0343831  0.38455322 0.230883   0.57551898 0.
  0.13766338 0.78585146 0.79180431 0.53755066]
 [0.79532557 0.16034497 0.50972741 0.35694944 0.45395074 0.13766338
  0.         0.76956198 0.69710671 0.46376357]
 [0.33493555 0.81731454 0.76890716 0.95494187 1.07174206 0.78585146
  0.76956198 0.         0.47949701 0.39240775]
 [0.19635252 0.82557066 0.98457614 1.01810265 0.77950087 0.79180431
  0.69710671 0.47949701

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [87]:
convert = np.arange(10, dtype=np.int32)
convert2 = convert.astype(np.float32, copy=False)
print(convert)
print(convert2)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [88]:
from io import StringIO
s=StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
z=np.genfromtxt(s, delimiter=",", dtype=int)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [89]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [90]:
X, Y = np.meshgrid(np.linspace(0,1,3), np.linspace(0,1,3))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[1.         0.8824969  0.60653066]
 [0.8824969  0.77880078 0.53526143]
 [0.60653066 0.53526143 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [91]:
n = 3
p = 5
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [92]:
X = np.random.rand(3,3)

In [93]:
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.22768406 -0.18402678  0.41171084]
 [ 0.31898873 -0.17101943 -0.1479693 ]
 [-0.01745704  0.18342189 -0.16596485]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [94]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 5 6]
 [7 0 6]
 [4 3 4]]
[[7 0 6]
 [4 3 4]
 [8 5 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [95]:
Z=np.zeros(4).reshape(2,2)
print(Z)
print((~Z.any(axis=0)).any())
X=np.ones(4).reshape(2,2)
print(X)
print((~X.any(axis=0)).any())

[[0. 0.]
 [0. 0.]]
True
[[1. 1.]
 [1. 1.]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [96]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5181747018319302


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [97]:
A=np.arange(3).reshape(3,1)
B=np.arange(3).reshape(1,3)
it=np.nditer([A,B,None])
for x,y,z in it:z[...]=x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [98]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [99]:
a=np.ones(10)
b=np.random.randint(0,len(a),10)
a+=np.bincount(b,minlength=len(a))
print(a)
np.add.at(a,b,1)
print(a)

[3. 1. 2. 1. 5. 2. 1. 2. 1. 2.]
[5. 1. 3. 1. 9. 3. 1. 3. 1. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [100]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [101]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

4


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [102]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[68 46 41 54]
 [52 60 36 43]
 [35 50 64 46]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [103]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.62205928 0.44797512 0.451278   0.40102734 0.63669203 0.52674278
 0.47532016 0.49470416 0.50370609 0.51220006]
0    0.622059
1    0.447975
2    0.451278
3    0.401027
4    0.636692
5    0.526743
6    0.475320
7    0.494704
8    0.503706
9    0.512200
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [104]:
arr1 = np.arange(1,10)
arr2 = np.arange(10,19)

In [105]:
arr1.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
arr2.reshape((3,3))

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [107]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [108]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [109]:
A = np.arange(4).reshape(2,2)
A[[0,1]] = A[[1,0]]
print(A)

[[2 3]
 [0 1]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [110]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  8) ( 0, 33) ( 8, 33) (10, 25) (10, 38) (16, 17) (16, 64) (17, 64)
 (21, 28) (21, 75) (23, 61) (23, 94) (24, 51) (24, 60) (25, 35) (25, 38)
 (25, 79) (27, 38) (27, 78) (28, 75) (29, 42) (29, 91) (32, 45) (32, 70)
 (35, 79) (38, 78) (42, 91) (45, 70) (51, 60) (61, 94)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [111]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [112]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [113]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(9), 5)
print(Z)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [114]:
Z = np.random.randint(0,2,10)
print ('original: ')
print (Z)
print('Negating a boolean: ')
print(np.logical_not(Z, out=Z))
print ('Change the sign of float inplace: ')
print(np.negative(Z, out=Z))

original: 
[0 1 1 1 1 1 0 1 1 0]
Negating a boolean: 
[1 0 0 0 0 0 1 0 0 1]
Change the sign of float inplace: 
[-1  0  0  0  0  0 -1  0  0 -1]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [115]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

In [116]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 5.51091159  2.7164424  11.60583414  5.89090873 10.0446876  11.22606499
  7.28165959  2.74504502  2.83740136 10.08582826]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [117]:
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 5.51091159  2.7164424  11.60583414  5.89090873 10.0446876  11.22606499
   7.28165959  2.74504502  2.83740136 10.08582826]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [118]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

In [119]:
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

In [120]:
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

In [121]:
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

In [122]:
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 9 4 2 8 8 5 5 1 2]
 [0 0 4 6 4 9 0 7 2 7]
 [0 5 2 4 7 8 2 3 7 0]
 [1 3 0 5 4 5 9 9 0 9]
 [2 2 6 2 2 8 7 8 3 3]
 [8 1 2 1 5 0 8 5 4 3]
 [5 9 4 3 5 2 9 4 2 9]
 [9 3 9 9 4 7 6 7 3 4]
 [9 8 3 0 5 8 1 3 2 9]
 [5 6 2 9 7 5 0 6 3 4]]
[[0 0 0 0 0]
 [0 4 9 4 2]
 [0 0 0 4 6]
 [0 0 5 2 4]
 [0 1 3 0 5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  This is separate from the ipykernel package so we can avoid doing imports until


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [123]:
Z = np.arange(1,15,dtype=int)

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(Z, 4)
print ('original: ')
print (Z)
print ('after strides: ')
print(R)

original: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
after strides: 
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [124]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print (rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [125]:
a=np.random.randint(1,10,5)
np.bincount(a).argmax()

3

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [126]:
Z=np.random.randint(0,5,(10,10))
from numpy.lib import stride_tricks
n=3
i=1+(Z.shape[0]-3)
j=1+(Z.shape[1]-3)
C=stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 3 4]
   [4 1 0]
   [4 3 3]]

  [[3 4 1]
   [1 0 4]
   [3 3 4]]

  [[4 1 4]
   [0 4 0]
   [3 4 3]]

  [[1 4 1]
   [4 0 3]
   [4 3 0]]

  [[4 1 0]
   [0 3 0]
   [3 0 2]]

  [[1 0 3]
   [3 0 1]
   [0 2 4]]

  [[0 3 2]
   [0 1 1]
   [2 4 2]]

  [[3 2 4]
   [1 1 3]
   [4 2 0]]]


 [[[4 1 0]
   [4 3 3]
   [0 2 4]]

  [[1 0 4]
   [3 3 4]
   [2 4 1]]

  [[0 4 0]
   [3 4 3]
   [4 1 4]]

  [[4 0 3]
   [4 3 0]
   [1 4 2]]

  [[0 3 0]
   [3 0 2]
   [4 2 3]]

  [[3 0 1]
   [0 2 4]
   [2 3 2]]

  [[0 1 1]
   [2 4 2]
   [3 2 0]]

  [[1 1 3]
   [4 2 0]
   [2 0 2]]]


 [[[4 3 3]
   [0 2 4]
   [3 2 3]]

  [[3 3 4]
   [2 4 1]
   [2 3 1]]

  [[3 4 3]
   [4 1 4]
   [3 1 0]]

  [[4 3 0]
   [1 4 2]
   [1 0 2]]

  [[3 0 2]
   [4 2 3]
   [0 2 3]]

  [[0 2 4]
   [2 3 2]
   [2 3 3]]

  [[2 4 2]
   [3 2 0]
   [3 3 0]]

  [[4 2 0]
   [2 0 2]
   [3 0 1]]]


 [[[0 2 4]
   [3 2 3]
   [3 4 0]]

  [[2 4 1]
   [2 3 1]
   [4 0 4]]

  [[4 1 4]
   [3 1 0]
   [0 4 0]]

  [[1 4 2]
   [1 0 2]
   [4 0 2]]

  [[4 2 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [127]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7  0 10 13 15]
 [ 0  4 10  4 11]
 [10 10  5 42  6]
 [13  4 42  5  8]
 [15 11  6  8  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [128]:
p,n= 10, 20
M=np.ones((p,n,n))
V=np.ones((p,n,1))
S=np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [129]:
Z=np.ones((16,16))
k=4
S=np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [130]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(10): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1
  0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0
  0 0 0 1 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 1 0 0
  0 0 1 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 1 1 1 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 0 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1
  1 0 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1
  0 1 1 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [131]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[95 96 97 98 99]
[98 96 97 99 95]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [132]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [133]:
z=np.array([("hello",2.5,3),
            ("world",3.6,2)])
r=np.core.records.fromarrays(z.T,names='col1,col2,col3',formats='S8,f8,i8')
print(r)

[(b'hello', 2.5, 3) (b'world', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [134]:
x=np.random.random(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.69 s per loop
10 loops, best of 5: 140 ms per loop
10 loops, best of 5: 123 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [135]:
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
C=(A[..., np.newaxis, np.newaxis] == B)
rows=np.where(C.any((3,1)).all(1))[0]
print(rows)

[2 3 4 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [136]:
Z=np.random.randint(0,5,(10,3))
print(Z)
E=np.all(Z[:,1:] == Z[:,:-1], axis=1)
U=Z[~E]
print(U)
U=Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 1 1]
 [0 2 1]
 [4 2 1]
 [3 3 1]
 [0 4 4]
 [3 2 2]
 [3 2 3]
 [1 0 0]
 [4 0 4]
 [2 0 2]]
[[0 1 1]
 [0 2 1]
 [4 2 1]
 [3 3 1]
 [0 4 4]
 [3 2 2]
 [3 2 3]
 [1 0 0]
 [4 0 4]
 [2 0 2]]
[[0 1 1]
 [0 2 1]
 [4 2 1]
 [3 3 1]
 [0 4 4]
 [3 2 2]
 [3 2 3]
 [1 0 0]
 [4 0 4]
 [2 0 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [137]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [138]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [139]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[5.33493042e-01, 2.76791842e-01, 5.10252809e-01, 2.09661676e-01,
        5.25215053e-01, 2.72189079e-01, 9.92178243e-02, 2.78709228e-03,
        2.26764853e-01, 2.06412252e-01],
       [2.61314597e-01, 1.35577679e-01, 2.49931108e-01, 1.02696103e-01,
        2.57259887e-01, 1.33323162e-01, 4.85986952e-02, 1.36516850e-03,
        1.11073550e-01, 1.01104476e-01],
       [2.32261693e-02, 1.20504180e-02, 2.22143818e-02, 9.12783707e-03,
        2.28657785e-02, 1.18500320e-02, 4.31955021e-03, 1.21338934e-04,
        9.87244154e-03, 8.98637006e-03],
       [6.46684061e-01, 3.35518663e-01, 6.18512956e-01, 2.54145515e-01,
        6.36649734e-01, 3.29939334e-01, 1.20268833e-01, 3.37842861e-03,
        2.74877467e-01, 2.50206662e-01],
       [6.16193217e-01, 3.19699119e-01, 5.89350366e-01, 2.42162675e-01,
        6.06632004e-01, 3.14382852e-01, 1.14598215e-01, 3.21913732e-03,
        2.61917126e-01, 2.38409538e-01],
       [5.04122344e-01, 2.61553462e-01, 4.82161569e-01, 1.98119051e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [140]:
phi = np.arange(0,10*np.pi,0.1)
phi

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9,
       11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. ,
       12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1,
       13.2, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2,
       14.3, 14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15

In [141]:
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

In [142]:
dr = (np.diff(x)**2 + np.diff(y)**2)**0.5

In [143]:
r=np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0,r.max(),200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [144]:
X=np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n=4
M=np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M&=(X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [145]:
X=np.random.randn(100) 
N=1000 
idx=np.random.randint(0, X.size, (N, X.size))
means=X[idx].mean(axis=1)
confint=np.percentile(means, [2.5, 97.5])
print(confint)

[-0.37385356  0.02956644]
